[INFO    ] [Client  ] Initializing client
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
[INFO    ] [Client  ] Logged on as freefbot#3056
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "lel" is not found
Ignoring exception in command None:
discord.ext.commands.errors.CommandNotFound: Command "adssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssadssssssssssssssssssssssssssssssssssssssssssssssssssssssss" is not found
Ignoring exception in command log:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\jakub\Desktop\freefbot\src\commands.py", line 120, in log
    await ctx.send(f'```python\n{Logger.get_log()[-2000:]}```')
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\abc.py", line 772, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\http.py", line 214, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In content: Must be 2000 or fewer in length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 615, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400): Invalid Form Body
In content: Must be 2000 or fewer in length.
